### ISSUE TITLE
Opening Graph Presets hangs

### ISSUE THREAD

**Issue by autonomygaps** [ycnmhd/obsidian-graph-presets#11]
I was really loving the Graph Presets, but now I'm having trouble. When using the command "Graph Presets: Open", it just hangs, as if it's searching for a file. but it does the same it I try to open one of the files I've previously created in Graph Presets.  The search bar keeps swiping across the top.

I'm running Version 1.2.6 (Installer 1.1.9) on a Mac.  Here is the error report from console in Obsidian:

plugin:obsidian-graph-presets:43199 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'instance')
at GraphPresets.registerMonkeyPatches (plugin:obsidian-graph-presets:43199:50)  
- at GraphPresets.onload (plugin:obsidian-graph-presets:43166:10)  
- at e.load (app.js:1:732280)  
- at e.<anonymous> (app.js:1:1919781)  
- at app.js:1:235927 at Object.next (app.js:1:236032)  
- at a (app.js:1:234750)

**Comment by ycnmhd** [comment]
I can't reproduce the bug, but given the error message, I suspect this bug has to do with with the "Starred" core plugin being removed in [Obsidian 1.2](https://forum.obsidian.md/t/obsidian-release-v1-2-0-insider-build/57173).

Please update to version [0.9.1](https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.9.1) and check if it's fixed.

**Comment by autonomygaps** [comment]
Thanks!  That takes care of it for me.  I'm still trying to figure out how to use it.  Some further documentation would be helpful.  What I'd love is a hotkey that I can hit, that just applied a saved graph preset to the currently focal graph pane.

**Comment by ycnmhd** [comment]
In Obsidian, a plugin can create commands, and a hotkey can be assigned to these commands.

To create a hotkey for applying a preset, do the following:
1. Enable "Create commands for presets" setting in the plugin settings (and restart obsidian)
![Pasted image 20230430071948](https://user-images.githubusercontent.com/33285087/235340430-f8023cbb-67c9-4dc1-9620-ee6d864f504f.png)

2. Go to "hotkeys", search for your preset by name, and assign a hotkey
![Pasted image 20230430071929](https://user-images.githubusercontent.com/33285087/235340459-78711463-389b-44e0-8fa6-b918e6242d88.png)

**Comment by autonomygaps** [comment]
Thanks, by the way, for the tip about a hotkey.  I should have figured that out myself!
