### ISSUE TITLE
Applying a preset to different local graphs without saving it as a snapshot of a note linked to its local graph

### ISSUE THREAD

**Issue by autonomygaps** [ycnmhd/obsidian-graph-presets#13]
I have a feature request that would make this plugin do something that Obsidian's "Bookmarks" doesn't do: to apply a preset to local graphs without saving it as a snapshot of a note linked to its local graph.

The new Bookmarks feature in Obsidian 1.2 makes it easy to save and manage graph presets. For the full-vault graph, that basically duplicates the functionality of this preset.  As I understand it, the "Graph Presets" adds a way to save snapshots of a note linked to a local graph, with the relevant graph settings, which is great.

But what I've been missing for a long time - [in a forum post in January 2021!](https://forum.obsidian.md/t/adjustable-persistent-settings-from-local-graph/11195) – is the ability to apply specific graph settings to an open local graph.  What currently happens is that if I save a preset that is based on a local graph and then try to apply those settings to the local graph of another note, it opens the pairing of the original note with its local graph.  I just want to apply the settings, without opening a different note.

Is that possible already?  Or is this a feature request you could take on?

**Comment by ycnmhd** [comment]
When a preset is applied to a local graph, it becomes bound to it (when the preset is applied later, it reopens the bound local graph, and then applies settings to it. This feature [was requested by morecup](https://github.com/ycnmhd/obsidian-graph-presets/issues/9#issuecomment-1482654770)).

To apply the preset to another local graph, you need to first unlink it from its current local graph:
1. Using the action button. 
![image](https://user-images.githubusercontent.com/33285087/235340251-fa08a3ee-74d3-4e81-b43f-f8679eb9e2bc.png)

2. Selecting a different local graph file from the preset settings.
![image](https://user-images.githubusercontent.com/33285087/235340311-0832f41f-95eb-4016-991c-0d03b4fbf467.png)

**Comment by autonomygaps** [comment]
Thanks so much for your swift response!  This is really going to be a game-changer for me, in combination with Bookmarks.
#### But I'm still struggling for how to deploy this in the following situation:
1. I've been working on a new note and I've added a bunch of links.
2. I open the local graph for that note, to start using the local graph settings to exploring related notes.
3. But the settings for the local graph aren't right – nothing is set (usually, for a new note), or the colors are from another setting.
4. What I want to do is apply the **_settings_** from one of my graph presets to the local graph of the current note.

Currently, at step 4, if I open the graph preset index, and right-click on one of my presets and select "apply preset" then the preset is saved as a preset that is bound to the current file.  But I want to leave the preset unchanged, so that I can apply it to any new situation I'm in.
Is that already possible?

**Comment by ycnmhd** [comment]
Applying the preset to a local graph without binding it is currently not possible.

There are multiple possible implementations to address this:
1. An "auto bind" global setting (to disable auto binding for all presets).
2. An "auto bind" preset setting (scoped to preset).
3. An "apply without binding" context menu option.
4. Prevent binding if the control key is pressed.

Which implementation do you prefer?

**Comment by autonomygaps** [comment]
Terrific!  I think that option "2" would be best, but I would title the toggle "Apply without binding to current file".  That would be clearest, I think.

How does this work for "update preset"?  Does this automatically change the binding?

All options would be great, of course!

**Comment by ycnmhd** [comment]
I've added the toggle to preset settings in version [0.10.0](https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.10.0).
The new setting affects both "apply preset" and "update preset".

The default value of this toggle can be set in the global settings (serves as the default value for newly created files, but does not affect existing presets)

**Comment by autonomygaps** [comment]
Wow!!!  That gives me exactly want I've been needing – for two and a half years!  With Keyboard Shortcuts, I can also map onto a single keystroke "open local graph" and "apply graph preset - default local graph".   What is also great about this is that it becomes easy to apply specific filtered local graphs to a note, revealing for example all notes with specific years in the filename or that contain particular names.

**Comment by autonomygaps** [comment]
Just posted a comment about this to the Obsidian forum:  https://forum.obsidian.md/t/adjustable-persistent-settings-from-local-graph/11195/38

**Comment by ycnmhd** [comment]
I'm glad this feature is helpful to you.

If you have any more suggestions, please don't hesitate.

**Comment by autonomygaps** [comment]
I’ve posted to Mastodon, the Obsidian forum, and the Obsidian Discord.
I'm really excited about the potential of the new Obsidian Graph Presets plugin, for applying saved settings to a LOCAL graph:
https://forum.obsidian.md/t/using-graph-preset-plugin-to-apply-graph-settings-to-local-graphs/58880 <https://forum.obsidian.md/t/using-graph-preset-plugin-to-apply-graph-settings-to-local-graphs/58880?u=autonomygaps>

Hope this gets you some traffic!

Joel
