### ISSUE TITLE
Show pages with similar tags in the local graph

### ISSUE THREAD

**Issue by Dev98248** [ycnmhd/obsidian-graph-presets#14]
By any chance does this plugin handle this feature?

**Use case or problem**
I love the local graph. It gives a better overview over a specific topic than the general graph. However, one thing I’ve noticed is that if I’m looking at the local graph of page A, which uses tag B, while page C also has tag B, page C is not visible in the local graph, no matter the depth. I think this would be pretty useful, since it helps you find related topics which haven’t been directly linked.

**Proposed solution**
If tags are enabled in the filters, and depth is more than 1, show pages which share tags with the page of the local graph. It already works in the general graph, but I think it would be useful to have this in the local graph as well.

https://forum.obsidian.md/t/show-pages-with-similar-tags-in-the-local-graph/11168

**Comment by ycnmhd** [comment]
Currently the plugin can't handle this feature.
It may be possible to implement (not sure).
It would require reverse-engineering the "graph" core plugin to understand how it works, and patching it using something like https://github.com/pjeby/monkey-around.

**Comment by Dev98248** [comment]
Ah ok understood. Thanks for the quick reply explaining that
