### ISSUE TITLE
Instructions for use unclear

### ISSUE THREAD

**Issue by robsyc** [ycnmhd/obsidian-graph-presets#15]
Sorry to have to post this here but I am hoping to use this plugin to save my local-graph preferences. I've made the `obsidian-graph-presets` folder under `/plugin` and added the 3 files from the release.

But I don't quite understand what is meant by "Create a new `preset `using the `presets-list view`". Is this a view in the same sense that the `editing` and `reading` views are views? If so how can I get into this view? There doesn't seem to be a button or command for it.

Or do I have to perform an extra step to make sure the 3 files for the plugin are properly read by Obsidian? Kind regards.

**Comment by ycnmhd** [comment]
I apologize for the incomplete installation instructions.

> I've made the `obsidian-graph-presets` folder under `/plugin` and added the 3 files from the release.


After you copy the files, you then need to (1) refresh the plugins list and (2) enable the plugin.
[this video](https://youtu.be/ffGfVBLDI_0?si=Kv9uJl_4eV5NhEdF&t=155) shows how to do it.

> But I don't quite understand what is meant by "Create a new `preset` using the `presets-list view`"

The `presets-list view` is a sidebar view that should appear automatically when the plugin is enabled.
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/33285087/00d122f0-490e-46a8-80b5-16308534ff38)

**Comment by robsyc** [comment]
I was hoping for this plugin to help me apply filters/groups/... settings to my **local** graph, however, whenever I open a local graph, it is still displayed in default style

[Original issue I posted on Obsidian forums](https://forum.obsidian.md/t/save-local-graph-preferences-just-like-the-ordinary-graph-view/75725)

**Comment by robsyc** [comment]
Okay, I've made 2 preset files: `global-graph` and `local-graph`

The way I'm getting around it is currently like this:

1. I'm in some random note
2. Within this note: Open linked view > Open local graph
3. Both windows are now side-by-side and I click the `preset-list view` button
4. I right click on my `local-graph` preset and click `Apply preset`

This works and is better than the alternative of having to apply all the individual settings of my local graph, every time I open a local graph.

But it would still be preferred if it would just always refer back to the `local-graph` preset whenever I open a local graph. Is this possible?

Edit: additionaly, is it possible to color the central node of the local graph (the node corresponding to the current note) differently?

**Comment by ycnmhd** [comment]
> But it would still be preferred if it would just always refer back to the local-graph preset whenever I open a local graph.

I'm not sure if this is what you are looking for, but the plugin has a feature where it can bind a preset to a file.
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/33285087/0e5c702d-3fdf-48a9-b2aa-6934805a8633)

For example, if a preset P is bound to a file A.md, when you apply preset P, it automatically opens A.md's local graph, and applies the preset to it

Bound presets are rendered with an arrow in the presets-list 
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/33285087/1876546a-c5cd-48fc-a646-789df206a1d1)

**Comment by robsyc** [comment]
Well it's rather that I don't want to bind it to any specific file and always have the preset activate whenever I open a local graph (from any note).

Similar to the behaviour of the default global graph view, which attains settings - as apposed to the default local graph. But this plugin already made my life much easier! Thank you 😄

**Comment by ycnmhd** [comment]
I think I can add a `target: "global" | "local"` setting to presets

**Comment by ycnmhd** [comment]
Update to https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.11.0 and see if the new `target` setting matches you request!

**Comment by gurguven** [comment]
> > But it would still be preferred if it would just always refer back to the local-graph preset whenever I open a local graph.
> 
> I'm not sure if this is what you are looking for, but the plugin has a feature where it can bind a preset to a file. ![image](https://private-user-images.githubusercontent.com/33285087/309071392-0e5c702d-3fdf-48a9-b2aa-6934805a8633.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTI3NzEsIm5iZiI6MTcxMDUxMjQ3MSwicGF0aCI6Ii8zMzI4NTA4Ny8zMDkwNzEzOTItMGU1YzcwMmQtM2ZkZi00OGE5LWIyYWEtNjkzNDgwNWE4NjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE0MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjZhZDAxZTg4NmQyZjhjNTE4ODE3M2QxMzdmZWVkMjdlMDYwOTdjYTE3MTYyNWFlNzYzMjZlYzA0MDkyN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QRZzm3Upn5r84aIYpJD-MsQEqVmzbqMFM0Yxc-RKcCs)
> 
> For example, if a preset P is bound to a file A.md, when you apply preset P, it automatically opens A.md's local graph, and applies the preset to it
> 
> Bound presets are rendered with an arrow in the presets-list ![image](https://private-user-images.githubusercontent.com/33285087/309070643-1876546a-c5cd-48fc-a646-789df206a1d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTI3NzEsIm5iZiI6MTcxMDUxMjQ3MSwicGF0aCI6Ii8zMzI4NTA4Ny8zMDkwNzA2NDMtMTg3NjU0NmEtYzVjZC00OGZjLWE2NDYtNzg5ZGYyMDZhMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE0MjExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjMwNzNlMDBmZDNkMzE5NzUzM2Y3Nzk0ZjJjYWY0MWZiZjJiMmZmZWMzZTczNDc4NmI3NjczODhhNTFjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mJeh4o8p9rw7i5xQTICm5FJeDzL4cH2VksDQNId-lw)

![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/91473262/02b2ed54-8317-4616-a406-64c8e9cd289e)

My preset settings are empty
