### ISSUE TITLE
Can't see anything inside the preset view

### ISSUE THREAD

**Issue by gurguven** [ycnmhd/obsidian-graph-presets#17]
I've took the 3 files, (main.js, styles & manifest), activated the plugin.... 

When I see your screenshot, we can see that you have some information on this "view" 
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/91473262/dbe229c3-9e07-4961-af3d-92cbee5e4c3b)

But as you can see on my screenshot, it's completely empty for me, I cannot change/save filters, groups or anything...
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/91473262/9091fe49-4d61-4776-8fad-95f58dfc7b3d)

Do you have an email to discuss this directly together ?

**Comment by ycnmhd** [comment]
Please try the latest release https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.11.1 and see if the bug persists

Edit: presets created with the previous release are empty.  you need to try with new presets

**Comment by gurguven** [comment]
I see now the filters ! 
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/91473262/5b27325f-3b48-4bde-a252-ae7923146032)

But a new trouble is there, I will create a new issue
