### ISSUE TITLE
tree-item-icon is misplaced on tree-item hover (preset view)

### ISSUE THREAD

**Issue by gurguven** [ycnmhd/obsidian-graph-presets#19]
As you can see here : 
![image](https://github.com/ycnmhd/obsidian-graph-presets/assets/91473262/486d65f4-2edf-4b90-a8f2-8b9f42510486)

On hover of each tree-item block (filters, groups, display..., 
the Apply Group tree-item-icon is misplaced (red cross) 
One patch could be to put "right: 0" to it.

**Comment by ycnmhd** [comment]
Thank you for reporting it.
I fixed the CSS in https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.11.2
