### ISSUE TITLE
Allow preset to be applied to local graph

### ISSUE THREAD

**Issue by sunyatasattva** [ycnmhd/obsidian-graph-presets#2]
When I open a local graph, and apply the preset, the preset still gets applied to the global graph. In the same way, the preset doesn't get saved or updated from a local graph, which caused me some headaches as I didn't understand why I couldn't get the preset saving to work.

**Comment by ycnmhd** [comment]
The plugin only works with the global graph ([current implementation](https://github.com/ycnmhd/obsidian-graph-presets/blob/86f6f1788d83bf8659b67a523f36001e0ef8c5a0/src/obsidian/apply-graph-settings.ts#L10))  
Good suggestion. I will try to add support for local graphs.

**Comment by ycnmhd** [comment]
Implemented in 888085de442f769e647124e3b60beca2d1d34600

**Comment by sunyatasattva** [comment]
That's brilliant! Thank you so much :)
