### ISSUE TITLE
Can't click files

### ISSUE THREAD

**Issue by dianatura** [ycnmhd/obsidian-graph-presets#5]
With your plugin enabled, I cannot open / interact with notes from either the files view or graph view.

Thanks for the plugin tho, especially the local graph feature!

**Comment by ycnmhd** [comment]
I'm aware of this bug (I think it started happening in version 0.6.0), but I don't know how to reproduce it deterministically. If you can provide a minimum reproduction vault that would be helpful.  
Nevertheless, I'm currently refactoring the code and rewriting state management, and that will hopefully get rid of the bug.

**Comment by ycnmhd** [comment]
@dianatura Please update to [0.7.1](https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.7.1) and see if the bug is still happening.

**Comment by Hunter-Bobeck** [comment]
I haven't noticed this issue yet on v.0.80. It may have been fixed.
