### ISSUE TITLE
[Feature Request] Add an additional button next to the 'Copy' button in codeblocks, to 'Load as graph filter'

### ISSUE THREAD

**Issue by Hunter-Bobeck** [ycnmhd/obsidian-graph-presets#8]
Hi,

This plugin is super helpful! Thank you for making it. It begins to ease the process of navigating the graph view.

Up until now, I have been storing many graph filters I regularly use, within codeblocks. It would take me a while to migrate them all over to being entire graph presets.
As part of this plugin, could you add a feature to Obsidian where it adds a button next to the 'Copy' button in each markdown codeblock, labeled 'Load as graph filter', which applies that code to be the filter of the current graph view? It would make the process of migrating to presets so much easier.

Thank you for considering!

**Comment by ycnmhd** [comment]
Hi, sorry for the late response. 
I think that automating the process using a script may be easier.
If you can share a sample file, I can try writing a nodejs script for you.
