### ISSUE TITLE
Can support it?

### ISSUE THREAD

**Issue by morecup** [ycnmhd/obsidian-graph-presets#9]
![图片](https://user-images.githubusercontent.com/103871318/227284323-c472ba26-d63a-4e14-9bd7-8b477f229db1.png)
![图片](https://user-images.githubusercontent.com/103871318/227284221-685b3df2-38ef-429c-81bc-332c8db3f7f3.png)

I always change depth to build graph ，Can support such ”Graph of filename“?

**Comment by ycnmhd** [comment]
if I understand correctly, you are asking if the plugin supports local graph? if this is the question, then the answer is yes. 
![2023-03-23_21-52-16](https://user-images.githubusercontent.com/33285087/227357737-5b12ff48-f05a-4db2-a90d-97885d03f026.gif).

**Comment by morecup** [comment]
Perhaps I was wrong. When I wanted to organize my ideas through graph, I first opened the presets file I saved at the time, and then clicked Apply to view the effect. I thought it would be a local graph, but in fact, it generated a global graph. Now I know that I need to open the corresponding file, open the local graph window, and apply the presets file. I think it's too cumbersome, don't you think?

**Comment by ycnmhd** [comment]
I see. it is cumbersome indeed.
I'll try to improve local graph workflow.

**Comment by morecup** [comment]
This plugin has been a great help to me, thank you. In my humble opinion, should local graph presets be bound to the md file by default? But can it also be used for other md files? I don't know if this is a good idea. Perhaps it should be set for users themselves?

**Comment by ycnmhd** [comment]
I'm imagining (1) the preset would be bound to the original md file, and (2) there would be a menu to change the target (another md file / global graph). What do you think?

**Comment by morecup** [comment]
That's a great idea.No md file binding means global graph.

**Comment by morecup** [comment]
In the global graph view, you can see all presets, but I don't want to see them here. My approach is to use preset when naming preset file, and use -file:preset filtering in the global graph view. Is there a better way?

**Comment by ycnmhd** [comment]
Good suggestion. I suppose the plugin would append a configurable filter that excludes all presets (and other non desired files)

**Comment by ycnmhd** [comment]
Implemented in 71215dabb10f5ed9cdb2089372da78ad241a805e 350bc637376197d27d013ace86c84fe2a05aa305 and released in [0.9.0](https://github.com/ycnmhd/obsidian-graph-presets/releases/tag/0.9.0)

**Comment by morecup** [comment]
I gave it a try. That's really great.Thank you so much!
